---
- name: Check Disk Space Usage
  hosts: all
  tasks:
          - name: Disk usage from command module
            shell: echo "START" ; uname -a ; sleep {{ tempo }} ; df -h ; echo "END"
            register: space
          - debug:
               var: space.stdout_lines
