---
- name: Check Disk Space Usage
  hosts: localhost
  tasks:
          - name: Disk usage from command module
            command: "echo START && sleep 10 && df -h && echo END"
            register: space
          - debug:
                  var: space.stdout_lines
